# my global config
global:
  scrape_interval:     5s 
  evaluation_interval: 5s
  external_labels:
      monitor: 'vg-mon'

scrape_configs:
  - job_name: 'node'
    static_configs:
    - targets: ['nodeexporter:9100']

  - job_name: 'nodejs'
    metrics_path: '/metrics'
    static_configs:
        - targets: ['webapp:8080']
